### ISSUE TITLE
Missing journal page permission

### ISSUE THREAD

**Issue by c-r-b-9** [benyar/pfs-provisions#5]
There's an issue a lot of GMs seem to run into. When sharing the journal with players, the players see an empty journal. That's because the permissions on the pages in the journal are unset. Once the GM sets those, the players can see the pages.

Setting the page permissions to "inherit" would make it so sharing/giving permission on the main journal is enough for players to see it. As there's no info in these journals that a GM might want to keep secret, I think this would be an easy solution.

And btw: Thanks for the very useful module!

**Comment by c-r-b-9** [comment]
Should add: I realize the README.md acknowledges this behavior and explains the workaround, but GMs I've talked to still run into it.

**Comment by benyar** [comment]
This is a known problem and I will work to try to fix.  Thank you.  :)

**Comment by benyar** [comment]
Corrected with 1.0.8.
